---
# tasks file for /usr/local/google/home/friasc/apigee-workspace/apigee-opdk-role-workspace/apigee-opdk-setup-postgres-db-upgrade
- name: Postgres master db_upgrade
  become_user: apigee
  shell: '/opt/apigee/apigee-service/bin/apigee-service apigee-postgresql db_upgrade'
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
    PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
    UP_TIMEOUT: '{{ up_timeout | default(60) }}'
  register: upgrade
  failed_when:
    - "'All OK' not in upgrade.stdout"
  when:
  - upgrade_from_opdk_version | version_compare('4.17.01', '<') and opdk_version | version_compare('4.17.09', '==')
  - opdk_version | version_compare('4.18.01', '==')
